"""Add password_changed_at column to user table

Revision ID: 360b16ba22c2
Revises: 
Create Date: 2025-06-09 17:20:52.015397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '360b16ba22c2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - adjusted by user ###
    
    # This is the ONLY operation we want to perform in this migration.
    # It adds the new 'password_changed_at' column to the 'users' table
    # within the 'vibesia_schema'.
    op.add_column(
        'users', 
        sa.Column('password_changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False), 
        schema='vibesia_schema'
    )
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - adjusted by user ###

    # This is the reverse operation. If we ever need to undo this migration,
    # it will simply drop the column we added.
    op.drop_column('users', 'password_changed_at', schema='vibesia_schema')

    # ### end Alembic commands ###